"""
Data models used throughout the BSP Merge Copilot.

These models define how information flows between modules.
"""

from dataclasses import dataclass, field

@dataclass(slots=True)
class Change:

    change_type: str          # ADDED / REMOVED / MODIFIED

    old_line: str

    new_line: str


@dataclass(slots=True)
class DiffSummary:

    filename: str

    relative_path: str

    vendor_diff: str

    customer_diff: str

    vendor_additions: int

    vendor_deletions: int

    customer_additions: int

    customer_deletions: int

    vendor_changes: list[Change] = field(default_factory=list)

    customer_changes: list[Change] = field(default_factory=list)

@dataclass(slots=True)
class FileBundle:
    """
    Represents one logical file across all three BSPs.

    Example:
        board.dts

        Base      -> board.dts
        Vendor    -> board.dts
        Customer  -> board.dts
    """

    filename: str
    relative_path: str

    base_content: str
    vendor_content: str
    customer_content: str

@dataclass(slots=True)
class FileDiff:
    """
    Stores generated diffs.

    Generated by diff_engine.py
    """

    filename: str
    relative_path: str

    vendor_diff: str
    customer_diff: str
